spring:
  application:
    name: consumer-feign
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 服务发现地址nacos的地
        namespace: ${spring.profiles.active}
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
        # 当前应用被sentinel监控的端口
        port: 8711

server:
  port: 9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

#sentinel
feign:
  sentinel:
    enabled: true