spring:
  application:
    name: spring-cloud-shardings
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ${spring.profiles.active}
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect



# 数据源 cloud-db-0,cloud-db-1
sharding:
  jdbc:
    datasource:
      names: cloud-db-0,cloud-db-1
    # 第一个数据库
      cloud-db-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://47.115.143.33:3306/cloud-db-0?characterEncoding=utf-8&&serverTimezone=GMT%2B8
        username: root
        password: 123456
    # 第二个数据库
      cloud-db-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://47.115.143.33:3306/cloud-db-1?characterEncoding=utf-8&&serverTimezone=GMT%2B8
        username: root
        password: 123456

# 水平拆分的数据库（表） 配置分库 + 分表策略 行表达式分片策略
# 分库策略
    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: id
            algorithm-expression: cloud-db-$->{id % 2}
        #分表策略 其中user为逻辑表 分表主要取决于age行
        tables:
           user:
             actual-data-nodes: cloud-db-$->{0..1}.user_$->{0..1}
             table-strategy:
               inline:
                 sharding-column: age
                 # 分片算法表达式
                 algorithm-expression: user_$->{age % 2}
      # 打印执行的数据库以及语句
      props:
        sql:
          show: true

server:
  port: 9967

