spring:
  application:
    name: spring-cloud-rabbitmq
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ${spring.profiles.active}

server:
  port: 9965

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
